packages:
  - '!com-gm112-rust-testlibrary/pkg'
  - com-gm112-rust-testlibrary/**/*
  - com-gm112-rust-testlibrary
  - com-gm112-rust-testproject/**/*
  - com-gm112-rust-testproject

catalog:
  '@types/node': ^25.2.2
  '@vitest/browser': ^4.0.18
  '@vitest/browser-playwright': ^4.0.18
  playwright: ^1.58.2
  prettier: ^3.8.1
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-wasm: ^3.5.0
  vitest: 4.0.18

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
