packages:
  - com-gm112-rust-testlibrary/**/*
  - com-gm112-rust-testlibrary
  - com-gm112-rust-testproject/**/*
  - com-gm112-rust-testproject

catalog:
  '@types/node': ^24.6.1
  '@vitest/browser': ^3.2.4
  playwright: ^1.55.1
  prettier: ^3.6.2
  typescript: ^5.9.3
  vite: ^7.1.7
  vite-plugin-wasm: ^3.5.0
  vitest: 3.2.4

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild
